### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by fruitTheory** [fruitTheory/file-renamer#3]
_Things to do:_

- Could add popup if extension already exists ("keep extension?")
- Implement selected files option or a way to ignore renaming folders ("checkbox")
- Implement image sharpener from other script (easy)

**Comment by Meyr991** [comment]
Hello :)
Found your project today, and I'm having some fun messing with it, can we chat a bit on discord?
Meyr#8803
:)

**Comment by fruitTheory** [comment]
Hey yeah if you have any ideas would be happy to hear. I think just posting here is ok or to do a pull request and can add on discord as well if needed.

**Comment by fruitTheory** [comment]
comp
